# This is a basic workflow to help you get started with Actions

name: GUT CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: croconut/godot-tester@v5.2
        with:
          # required
          version: "4.4.1"
          # the type of release of godot that the tests should be run with
          release_type: "stable"
          is-mono: "false"
          # how long to spend importing assets before tests are run
          import-time: "5"
          # how long tests can run in seconds
          test-timeout: "100"
          # the ratio of tests that must pass for this action to pass
          # e.g. 0.6 means 60% of your tests must pass
          minimum-pass: "0.9"
          # the directory containing Gut tests
          test-dir: "res://tests"
          # default is false, set true to count asserts instead of tests
          assert-check: "true" 
          # not checked by default, set to a number to limit the 
          # maximum amount of failed tests for a passing test suite
          max-fails: 1
          # default is GUTs default: 'res://.gutconfig.json'; set this to load a different config file
          config-file: "res://.gutconfig.json" 
          # designate a custom url to download the godot binary from (e.g. https://download_url.com/godot/example_download.zip)
          custom-godot-dl-url: "https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip"
          # designate a custom path to execute the godot binary (e.g. relative_filename.exe)
          custom-godot-binary-path: "Godot_v4.4.1-stable_linux.x86_64"
